server:
  port: 8555
spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/securityWithAdapter
    username: sa
    password: 1234

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 400
        use_sql_comments: true
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect